# enable logging
CONFIG_LOG=y

# enable BLE with extended periodic advertisement
CONFIG_BT=y
CONFIG_BT_EXT_ADV=y
CONFIG_BT_PER_ADV=y
# define BLE name for scan request
CONFIG_BT_DEVICE_NAME="TTF Periodic Advertiser"

# increase BLE range by setting TX power to +8dBm
# and using CODED PHY
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# CONFIG_BT_CTLR_PHY_CODED=y