# Tuff-Tuff-Light (TTL) West manifest repository
# Copyright (c) 2025 Rehka.dev

manifest:
  # use the latest version of the manifest format
  version: 1.2

  self:
    path: ttl

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  # Projects to manage with west
  projects:
    # ttl is based on the nrf sdk (based on nordic mcus)
    - name: sdk-nrf
      path: nrf
      remote: nrfconnect
      revision: v2.9.0
      import: true
