# Configure logger
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y

# Enable Bluetooth
CONFIG_BT=y
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="TuffTuffLight"

# Enable ws2812 led driver
CONFIG_SPI=y
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_DBG=y