# Configure logger
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
# Enable debug logging
CONFIG_LOG_DEFAULT_LEVEL=4

# Configure gpio
CONFIG_GPIO=y

# Enable Bluetooth
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_SMP=y
CONFIG_BT_GATT_CLIENT=y

# Enable Bluetooth multilink
CONFIG_BT_AUTO_PHY_UPDATE=n
CONFIG_BT_PRIVACY=y
CONFIG_BT_MAX_CONN=2

# Enable nrf scan utils (filter)
CONFIG_BT_SCAN=y
CONFIG_BT_SCAN_UUID_CNT=1
CONFIG_BT_SCAN_FILTER_ENABLE=y

# Enable nrf gatt discovery manager utils
CONFIG_BT_GATT_DM=y
CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_GATT_DM_DATA_PRINT=y

# This example requires more workqueue stack and heap
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Enable bonding
CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y